'use client';
import {useEffect,useState} from 'react';
import {BarChart,Bar,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend,ResponsiveContainer} from 'recharts';
import {RefreshCw,CalendarDays} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {categories,rupiah,type Product} from '@/lib/catalog';
import BrandLoading from '../brand-loading';
const periods=[['all','All-time'],['daily','Daily'],['weekly','Weekly'],['monthly','Monthly'],['yearly','Yearly'],['range','Range tanggal']];
const statuses=[['all','Semua'],['completed','Selesai'],['failed','Gagal'],['shipping','Dalam pengiriman']];
const colors=['#b82d38','#288c80','#9976d6','#d28a16','#4376ba'];
function Choice({label,value,onChange,choices}:{label:string;value:string;onChange:(v:string)=>void;choices:string[][]}){return <label className="analytics-choice"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger className="analytics-source-trigger" aria-label={label}><SelectValue/></SelectTrigger><SelectContent className="analytics-source-options" position="popper">{choices.map(([v,name])=><SelectItem key={v} value={v}>{name}</SelectItem>)}</SelectContent></Select></label>;}
const tick=(v:string)=>v.length===7?v.slice(5)+'/'+v.slice(0,4):v.slice(8)+'/'+v.slice(5,7);
export default function AnalyticsPanel({products}:{products:Product[]}){
 const [mode,setMode]=useState('demo'),[period,setPeriod]=useState('monthly'),[category,setCategory]=useState('all'),[status,setStatus]=useState('all'),[barPeriod,setBarPeriod]=useState('weekly'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[now,setNow]=useState<number|null>(null),[data,setData]=useState<any>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(true);
 useEffect(()=>{setNow(Date.now());const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[]);
 const valid=period!=='range'||(from&&to&&from<=to);
 useEffect(()=>{const controller=new AbortController();setError('');if(!valid){setLoading(false);setData(null);return()=>controller.abort();}setLoading(true);setData(null);const q=new URLSearchParams({mode,period,category,status,barPeriod,from,to});fetch('/api/admin/analytics?'+q,{signal:controller.signal}).then(async r=>{const d:any=await r.json();if(!r.ok)throw Error(d.error||'Analytics belum dapat dimuat.');return d;}).then(d=>{if(!controller.signal.aborted)setData(d);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[mode,period,category,status,barPeriod,from,to,refresh,valid]);
 const date=now?new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Jakarta',weekday:'long',day:'2-digit',month:'long',year:'numeric'}).formatToParts(now):[];
 const part=(key:string)=>date.find(p=>p.type===key)?.value||'—';
 const clock=now?new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Jakarta',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(now):'—';
 const tooltip={background:'var(--background)',color:'var(--foreground)',borderColor:'var(--border)',borderRadius:12};
 return <><div className="admin-toolbar analytics-toolbar"><div><h2>Analytics pembelian</h2><p className="analytics-context">{category==='all'?'Semua kategori':category} • <time>{clock} GMT+7</time> • Date: {part('weekday')}, {part('day')}-{part('month')}-{part('year')} • {statuses.find(s=>s[0]===status)?.[1]}</p></div><div className="analytics-source-actions"><Choice label="Sumber data" value={mode} onChange={setMode} choices={[["demo","Simulasi demo"],["xendit-test","Xendit Test"]]}/><button className="outline" disabled={loading||!valid} onClick={()=>setRefresh(n=>n+1)}><RefreshCw size={17}/>Perbarui</button></div></div>
 <section className="analytics-filters" aria-label="Filter analytics"><div className="analytics-periods" role="group" aria-label="Periode pembelian">{periods.map(([v,label])=><button key={v} className={period===v?'active':''} aria-pressed={period===v} onClick={()=>setPeriod(v)}>{v==='range'&&<CalendarDays size={16}/>} {label}</button>)}</div><div className="analytics-filter-row"><Choice label="Kategori" value={category} onChange={setCategory} choices={[["all","Semua kategori"],...Array.from(new Set([...categories.filter(c=>c!=='Semua Produk'),...products.map(p=>p.category)])).map(c=>[c,c])]}/><Choice label="Status pesanan" value={status} onChange={setStatus} choices={statuses}/>{period==='range'&&<><label>Dari tanggal<input type="date" value={from} max={to||undefined} onChange={e=>setFrom(e.target.value)}/></label><label>Sampai tanggal<input type="date" value={to} min={from||undefined} onChange={e=>setTo(e.target.value)}/></label></>}</div>{period==='range'&&!valid&&<p className="analytics-help" role="status">Pilih tanggal mulai dan akhir untuk melihat analytics.</p>}</section>
 {error&&<div className="admin-alert" role="alert">{error}<button className="outline" onClick={()=>setRefresh(n=>n+1)}>Coba lagi</button></div>}{loading&&<BrandLoading label="Memuat analytics…"/>}{data&&<>
 {data.inventoryAlerts?.length>0&&<div className="admin-alert"><strong>Periksa ketersediaan stok</strong><p>Pembayaran telah diterima, tetapi stok saat konfirmasi tidak mencukupi. Siapkan kekurangan barang sebelum pengiriman.</p>{data.inventoryAlerts.map((a:any)=><p key={a.id}>Pesanan #{a.id.slice(-8)}: {a.items.map((i:any)=>(products.find(p=>p.id===i.id)?.name||i.id)+' (kurang '+i.shortfall+')').join(', ')}</p>)}</div>}
 <div className="admin-metrics"><article><span>Pesanan sesuai filter</span><strong>{data.summary.matchingOrders}</strong></article><article><span>Unit terjual</span><strong>{data.units}</strong></article><article><span>Nilai pembelian {mode==='demo'?'demo':'Test'}</span><strong>{rupiah(data.summary.revenue)}</strong></article></div><p className="analytics-help">Unit dan nilai pembelian menghitung barang yang sudah dibayar. Dalam pengiriman mencakup pesanan dibayar yang belum diselesaikan.</p>
 {!data.units&&<p className="admin-empty">Belum ada barang terjual sesuai filter ini.</p>}
 <div className="admin-chart-grid">{(['Categories','Products'] as const).map(type=>{const entries=data['top'+type],prefix=type==='Categories'?'c':'p';return <section className="admin-surface" key={type}><h2>{type==='Categories'?'Kategori paling sering dibeli':'Barang paling sering dibeli'}</h2><p>Jumlah unit per {data.granularity==='monthly'?'bulan':'hari'} · lima teratas</p><div className="admin-chart" role="img" aria-label={'Grafik garis '+(type==='Categories'?'kategori':'produk')+' terlaris'}><ResponsiveContainer width="100%" height="100%"><LineChart data={data.days} margin={{top:10,right:16,bottom:8,left:0}}><CartesianGrid strokeDasharray="3 3" stroke="var(--border)"/><XAxis dataKey="day" tickFormatter={tick} minTickGap={35} tick={{fill:'var(--muted-foreground)',fontSize:12}}/><YAxis allowDecimals={false} width={35} tick={{fill:'var(--muted-foreground)',fontSize:12}}/><Tooltip contentStyle={tooltip}/><Legend/>{entries.map((p:any,i:number)=><Line key={p.id||p.name} type="monotone" dataKey={prefix+i} name={p.name} stroke={colors[i]} strokeWidth={2.5} dot={false} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer></div><ol className="admin-ranking">{entries.map((p:any,i:number)=><li key={p.id||p.name}><span><i style={{background:colors[i]}}/>{p.name}</span><b>{p.quantity} unit</b></li>)}</ol></section>;})}</div>
 <section className="admin-surface analytics-status-chart"><div className="admin-toolbar"><div><h2>Status penjualan</h2><p>Jumlah pesanan sukses dan gagal · {category==='all'?'semua kategori':category}</p></div><div className="analytics-periods" role="group" aria-label="Periode status penjualan">{periods.filter(([v])=>['weekly','monthly','yearly'].includes(v)).map(([v,label])=><button key={v} className={barPeriod===v?'active':''} aria-pressed={barPeriod===v} onClick={()=>setBarPeriod(v)}>{label}</button>)}</div></div><div className="admin-chart" role="img" aria-label="Grafik batang berdampingan jumlah pesanan sukses dan gagal"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.statusBars} barGap={4} margin={{top:10,right:16,bottom:8,left:0}}><CartesianGrid strokeDasharray="3 3" stroke="var(--border)" vertical={false}/><XAxis dataKey="day" tickFormatter={tick} minTickGap={25} tick={{fill:'var(--muted-foreground)',fontSize:12}}/><YAxis allowDecimals={false} width={35} tick={{fill:'var(--muted-foreground)',fontSize:12}}/><Tooltip contentStyle={tooltip}/><Legend/><Bar dataKey="success" name="Sukses" fill="#288c80" radius={[4,4,0,0]} maxBarSize={38} isAnimationActive={false}/><Bar dataKey="failed" name="Gagal" fill="#b82d38" radius={[4,4,0,0]} maxBarSize={38} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><p className="analytics-help">Sukses: pembayaran diterima atau pesanan selesai. Gagal: pembayaran gagal, dibatalkan, atau kedaluwarsa. Grafik ini membandingkan kedua status pada periode pilihannya, terpisah dari filter status di atas.</p><div className="analytics-status-totals"><span>Sukses <strong>{data.statusBars.reduce((s:number,r:any)=>s+r.success,0)}</strong></span><span>Gagal <strong>{data.statusBars.reduce((s:number,r:any)=>s+r.failed,0)}</strong></span></div></section>
 </>}</>;
}
