'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend,ResponsiveContainer} from 'recharts';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {categories,rupiah,type Product} from '@/lib/catalog';
import type {Staff} from '@/lib/managed-catalog';
import ThemeToggle from '../theme-toggle';
import ImagePicker from './image-picker';
import {Plus,Save,RefreshCw,LogOut,Pencil,Store,KeyRound} from 'lucide-react';
type Item=Product&{version:number};
const blank:Item={id:'',name:'',category:'Sembako',unit:'1 pcs',price:1000,stock:0,origin:'Gerai Koperasi',image:'',tag:'Sembako',packaged:true,trending:false,version:0};
const colors=['#b82d38','#288c80','#9976d6','#d28a16','#4376ba'];
export default function Dashboard(){const router=useRouter();const [user,setUser]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[uploadCount,setUploadCount]=useState(0),[products,setProducts]=useState<Item[]>([]),[staff,setStaff]=useState<Staff[]>([]),[staffVersion,setStaffVersion]=useState(0),[staffReady,setStaffReady]=useState(false),[analytics,setAnalytics]=useState<any>(null),[mode,setMode]=useState('demo'),[query,setQuery]=useState(''),[editing,setEditing]=useState<Item|null>(null),[creating,setCreating]=useState(false),[stockAdd,setStockAdd]=useState(1),[invite,setInvite]=useState<any>(null);
 function uploadBusy(value:boolean){setUploadCount(n=>Math.max(0,n+(value?1:-1)));}
 async function api(path:string,method='GET',body?:unknown){const r=await fetch('/api/admin/'+path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d:any=await r.json();if(r.status===401){router.replace('/admin/login');throw Error('Sesi admin berakhir. Silakan masuk kembali.');}if(!r.ok)throw Error(d.error||'Permintaan belum berhasil.');return d;}
 async function loadProducts(){const d=await api('products');setProducts(d.products);}
 async function loadStaff(){const d=await api('staff');setStaff(d.staff);setStaffVersion(d.version);setStaffReady(true);}
 async function loadAnalytics(){setAnalytics(null);const d=await api('analytics?mode='+mode);setAnalytics(d);}
 useEffect(()=>{let active=true;(async()=>{try{const d=await api('session');if(!d.user){router.replace('/admin/login');return;}if(!active)return;setUser(d.user);await Promise.all([loadProducts(),loadStaff()]);}catch(e){if(active)setError(e instanceof Error?e.message:'Data belum tersedia.');}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[]);
 useEffect(()=>{let active=true;if(user){setAnalytics(null);api('analytics?mode='+mode).then(d=>{if(active)setAnalytics(d);}).catch(e=>{if(active)setError(e.message);});}return()=>{active=false;};},[user,mode]);
 async function action(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Perubahan belum berhasil.');}finally{setBusy(false);}}
 async function saveProduct(){if(!editing||uploadCount>0)return;const {version,...product}=editing;await action(async()=>{const d=await api('products',creating?'POST':'PUT',{product,version});setProducts(d.products);setEditing(null);setNotice('Produk disimpan. Perubahan tampil di toko saat dimuat ulang atau pembaruan katalog berikutnya.');});}
 const filtered=products.filter(p=>(p.name+' '+p.category).toLowerCase().includes(query.toLowerCase()));
 if(loading)return <main className="admin-shell"><p role="status">Memuat admin…</p></main>;
 if(!user)return <main className="admin-auth">{error&&<p role="alert">{error}</p>}<Link href="/admin/login" className="primary">Login admin</Link></main>;
 return <main className="admin-shell"><header className="admin-header"><Link href="/" className="admin-brand"><img src="/kopdes-logo.png" alt="Kopdes"/>KOPDES <span>ADMIN</span></Link><div><ThemeToggle/><Link className="outline" href="/"><Store size={17}/>Lihat toko</Link><button className="outline" disabled={busy||uploadCount>0} onClick={()=>action(async()=>{await api('session','DELETE');router.replace('/admin/login');})}><LogOut size={17}/>Keluar</button></div></header><div className="admin-title"><p className="eyebrow">RUANG KERJA INTERNAL</p><h1>Selamat datang, {user.name}.</h1><p>Kelola kebutuhan toko dan lihat aktivitas pembelian.</p></div>{error&&<div className="admin-alert" role="alert">{error}</div>}{notice&&<div className="admin-success" role="status">{notice}</div>}<Tabs defaultValue="overview"><TabsList className="admin-tabs"><TabsTrigger value="overview">Beranda</TabsTrigger><TabsTrigger value="products">Produk & stok</TabsTrigger><TabsTrigger value="staff">Karyawan</TabsTrigger><TabsTrigger value="access">Akses internal</TabsTrigger></TabsList>
 <TabsContent value="overview"><div className="admin-toolbar"><div><h2>Analytics pembelian</h2><p>30 hari terakhir · zona waktu WIB · hanya pesanan dibayar/selesai.</p></div><label>Sumber data<select value={mode} onChange={e=>setMode(e.target.value)}><option value="demo">Simulasi demo</option><option value="xendit-test">Xendit Test</option></select></label><button className="outline" disabled={busy||uploadCount>0} onClick={()=>action(loadAnalytics)}><RefreshCw size={17}/>Perbarui</button></div>{analytics?<><div className="admin-metrics"><article><span>Pesanan dibayar</span><strong>{analytics.summary?.orders||0}</strong></article><article><span>Unit terjual</span><strong>{analytics.units}</strong></article><article><span>Nilai pembelian {mode==='demo'?'demo':'Test'}</span><strong>{rupiah(analytics.summary?.revenue||0)}</strong></article></div>{!analytics.units&&<p className="admin-empty">Belum ada pembelian dibayar pada periode ini. Grafik akan terisi dari pesanan, tanpa data contoh tambahan.</p>}<div className="admin-chart-grid">{(['Categories','Products'] as const).map(type=>{const entries=analytics['top'+type],prefix=type==='Categories'?'c':'p';return <section className="admin-surface" key={type}><h2>{type==='Categories'?'Kategori paling sering dibeli':'Barang paling sering dibeli'}</h2><p>Jumlah unit per hari · lima teratas</p><div className="admin-chart" role="img" aria-label={'Grafik garis '+(type==='Categories'?'kategori':'produk')+' terlaris, jumlah unit per hari'}><ResponsiveContainer width="100%" height="100%"><LineChart data={analytics.days} margin={{top:10,right:16,bottom:8,left:0}}><CartesianGrid strokeDasharray="3 3" stroke="var(--border)"/><XAxis dataKey="day" tickFormatter={v=>v.slice(8)+'/'+v.slice(5,7)} minTickGap={35} tick={{fill:'var(--muted-foreground)',fontSize:12}}/><YAxis allowDecimals={false} width={35} tick={{fill:'var(--muted-foreground)',fontSize:12}}/><Tooltip contentStyle={{background:'var(--background)',color:'var(--foreground)',borderColor:'var(--border)'}}/><Legend/>{entries.map((p:any,i:number)=><Line key={p.id||p.name} type="monotone" dataKey={prefix+i} name={p.name} stroke={colors[i]} strokeWidth={2.5} dot={false} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer></div><ol className="admin-ranking">{entries.map((p:any,i:number)=><li key={p.id||p.name}><span><i style={{background:colors[i]}}/>{p.name}</span><b>{p.quantity} unit</b></li>)}</ol></section>;})}</div></>:<p role="status">Memuat analytics…</p>}</TabsContent>
 <TabsContent value="products"><div className="admin-toolbar"><div><h2>Produk & stok</h2><p>{products.length} produk · {products.filter(p=>p.stock===0).length} stok kosong · {products.filter(p=>p.trending).length} trending</p></div><input aria-label="Cari produk admin" placeholder="Cari nama atau kategori…" value={query} onChange={e=>setQuery(e.target.value)}/><button className="outline" disabled={busy||uploadCount>0} onClick={()=>action(loadProducts)}><RefreshCw size={17}/>Muat ulang</button><button className="primary" onClick={()=>{setCreating(true);setEditing({...blank,id:'produk-'+Date.now()});setStockAdd(1);}}><Plus size={18}/>Tambah item</button></div><div className="admin-product-list">{filtered.map(p=><article key={p.id}><img src={p.image} alt=""/><div><h3>{p.name}</h3><p>{p.category} · {rupiah(p.price)} / {p.unit}</p><span className={p.stock?'admin-stock':'admin-out'}>{p.stock?'Stok: '+p.stock:'Stok kosong'}</span>{p.trending&&<span className="admin-trending">Trending</span>}</div><button className="outline" onClick={()=>{setCreating(false);setEditing({...p});setStockAdd(1);}}><Pencil size={16}/>Edit produk</button></article>)}{!filtered.length&&<p className="admin-empty">Tidak ada produk yang cocok.</p>}</div></TabsContent>
 <TabsContent value="staff"><div className="admin-toolbar"><div><h2>Halaman karyawan</h2><p>Edit gambar, nama, peran, urutan, dan visibilitas di toko.</p></div><button className="outline" disabled={busy||uploadCount>0} onClick={()=>action(loadStaff)}><RefreshCw size={17}/>Muat ulang</button><button className="primary" disabled={busy||uploadCount>0||!staffReady} onClick={()=>action(async()=>{const d=await api('staff','PUT',{staff,version:staffVersion});setStaffVersion(d.version);setNotice('Halaman karyawan berhasil diperbarui.');})}><Save size={17}/>Simpan karyawan</button></div><div className="admin-staff-list">{staff.map((s,i)=>{function update(key:keyof Staff,value:string|boolean){setStaff(old=>old.map((p,n)=>n===i?{...p,[key]:value}:p));}return <section className="admin-surface" key={s.id}><img className="admin-staff-preview" src={s.image} alt={s.role}/><div className="admin-form-grid"><label>Peran<input value={s.role} maxLength={80} onChange={e=>update('role',e.target.value)}/></label><label>Nama (opsional)<input value={s.name} maxLength={80} onChange={e=>update('name',e.target.value)}/></label><div className="wide"><ImagePicker value={s.image} label="Foto karyawan" onBusyChange={uploadBusy} onChange={value=>setStaff(old=>old.map(p=>p.id===s.id?{...p,image:value}:p))}/></div><label className="wide">Deskripsi<textarea value={s.description} maxLength={300} onChange={e=>update('description',e.target.value)}/></label><label className="admin-check"><input type="checkbox" checked={s.active} onChange={e=>update('active',e.target.checked)}/>Tampilkan di halaman karyawan</label><div className="admin-inline"><button className="outline" disabled={i===0} onClick={()=>setStaff(a=>{const n=[...a];[n[i-1],n[i]]=[n[i],n[i-1]];return n;})}>↑ Naik</button><button className="outline" disabled={i===staff.length-1} onClick={()=>setStaff(a=>{const n=[...a];[n[i+1],n[i]]=[n[i],n[i+1]];return n;})}>↓ Turun</button></div></div></section>;})}</div><button className="outline" disabled={!staffReady||staff.length>=30} onClick={()=>setStaff(s=>[...s,{id:'karyawan-'+Date.now(),name:'',role:'Karyawan baru',description:'',image:'/kopdes-logo.png',active:true}])}><Plus size={17}/>Tambah karyawan</button></TabsContent>
 <TabsContent value="access"><section className="admin-surface admin-access"><h2>Undang admin internal</h2><p>Setiap akun admin dapat mengelola toko dan mengundang admin lain. Bagikan kode hanya kepada tim yang berwenang.</p><p>Kode berlaku 24 jam dan hanya untuk satu pendaftaran.</p><button className="primary" disabled={busy||uploadCount>0} onClick={()=>action(async()=>{setInvite(await api('invites','POST'));})}><KeyRound size={17}/>Buat kode undangan</button>{invite&&<div className="admin-invite"><label>Kode undangan<input readOnly value={invite.code} onFocus={e=>e.target.select()}/></label><p>Berlaku hingga {new Date(invite.expiresAt).toLocaleString('id-ID')}</p><Link className="detail-link" href="/admin/register">Halaman pendaftaran admin ↗</Link></div>}<hr/><p>Login sebagai <strong>{user.email}</strong>. Sesi berakhir setelah 8 jam.</p></section></TabsContent></Tabs>
 <Dialog open={!!editing} onOpenChange={open=>{if(!open&&!busy&&uploadCount===0)setEditing(null);}}><DialogContent className="admin-product-dialog"><DialogHeader><DialogTitle>{creating?'Tambah item terbaru':'Edit produk & stok'}</DialogTitle><DialogDescription>Perubahan disimpan ke katalog toko. Stok kosong ditetapkan dengan jumlah 0.</DialogDescription></DialogHeader>{editing&&<form onSubmit={e=>{e.preventDefault();void saveProduct();}}><div className="admin-form-grid">{[{key:'name',label:'Nama produk'},{key:'unit',label:'Satuan'},{key:'origin',label:'Asal produk'}].map(f=><label key={f.key} className={f.key==='image'?'wide':''}>{f.label}<input required value={(editing as any)[f.key]} maxLength={f.key==='image'?2000:100} onChange={e=>setEditing({...editing,[f.key]:e.target.value})}/></label>)}<div className="wide"><ImagePicker key={editing.id} value={editing.image} label="Foto produk" onBusyChange={uploadBusy} onChange={image=>setEditing(old=>old?{...old,image}:old)}/></div><label>Kategori<select value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value,tag:e.target.value})}>{categories.filter(c=>c!=='Semua Produk').map(c=><option key={c}>{c}</option>)}</select></label><label>Harga (Rp)<input type="number" min={1} max={100000000} required value={editing.price} onChange={e=>setEditing({...editing,price:Number(e.target.value)})}/></label><label>Stok saat ini<input type="number" min={0} max={100000} required value={editing.stock} onChange={e=>setEditing({...editing,stock:Number(e.target.value)})}/></label><label>Tambahkan stok<div className="admin-inline"><input aria-label="Jumlah stok tambahan" type="number" min={1} max={100000} value={stockAdd} onChange={e=>setStockAdd(Number(e.target.value))}/><button type="button" className="outline" disabled={!Number.isInteger(stockAdd)||stockAdd<1||editing.stock+stockAdd>100000} onClick={()=>setEditing({...editing,stock:editing.stock+stockAdd})}>Tambah</button></div></label><button className="outline" type="button" onClick={()=>setEditing({...editing,stock:0})}>Tandai stok kosong</button><label className="admin-check"><input type="checkbox" checked={editing.trending} onChange={e=>setEditing({...editing,trending:e.target.checked})}/>Produk trending</label><label className="admin-check"><input type="checkbox" checked={editing.packaged} onChange={e=>setEditing({...editing,packaged:e.target.checked})}/>Foto produk kemasan (tampil utuh)</label></div>{error&&<p role="alert" className="error">{error}</p>}<div className="admin-form-actions"><button className="outline" type="button" disabled={busy||uploadCount>0} onClick={()=>setEditing(null)}>Batal</button><button className="primary" disabled={busy||uploadCount>0}><Save size={17}/>{busy?'Menyimpan…':'Simpan produk'}</button></div></form>}</DialogContent></Dialog></main>;
}
