import assert from 'node:assert/strict';
import {aggregateAnalytics,periodBounds,dateWIB} from '../lib/admin-analytics.ts';
const now=Date.parse('2026-10-04T12:00:00+07:00'),ms=s=>Date.parse(s);
assert.deepEqual(periodBounds('daily',now),{start:ms('2026-10-04T00:00:00+07:00'),end:ms('2026-10-05T00:00:00+07:00')});
assert.deepEqual(periodBounds('weekly',now),{start:ms('2026-09-28T00:00:00+07:00'),end:ms('2026-10-05T00:00:00+07:00')});
assert.equal(dateWIB(periodBounds('monthly',now).end),'2026-11-01');
assert.equal(dateWIB(periodBounds('yearly',now).end),'2027-01-01');
assert.throws(()=>periodBounds('range',now,'2026-02-30','2026-03-02'));
assert.throws(()=>periodBounds('range',now,'2026-10-04','2026-10-03'));
const items=[{id:'rice',name:'Beras',category:'Sembako',price:100,quantity:2},{id:'water',name:'Air',category:'Minuman',price:50,quantity:3}];
const order=(id,status,at='2026-10-04T00:00:00+07:00',list=items)=>({id,status,created_at:ms(at),paid_at:['PAID','COMPLETED'].includes(status)?ms(at):null,data:JSON.stringify({items:list,amount:350,expiresAt:now-1})});
const rows=[order('paid','PAID'),order('done','COMPLETED'),order('failed','FAILED'),order('expired','PENDING'),order('edge','COMPLETED','2026-10-05T00:00:00+07:00'),order('old','COMPLETED','2025-01-02T15:00:00+07:00')];
const opts={period:'daily',barPeriod:'weekly',category:'all',status:'all'};
let a=aggregateAnalytics(rows,opts,now);assert.equal(a.units,10);assert.equal(a.summary.orders,2);assert.equal(a.summary.matchingOrders,4);assert.equal(a.summary.revenue,700);assert.equal(a.statusBars.length,7);assert.deepEqual(a.statusBars.at(-1),{day:'2026-10-04',success:2,failed:2});
a=aggregateAnalytics(rows,{...opts,category:'Sembako'},now);assert.equal(a.units,4);assert.equal(a.summary.revenue,400);assert.equal(a.summary.orders,2);assert.equal(a.topProducts.length,1);
a=aggregateAnalytics(rows,{...opts,status:'failed'},now);assert.equal(a.units,0);assert.equal(a.summary.matchingOrders,2);assert.equal(a.statusBars.at(-1).success,2);
a=aggregateAnalytics(rows,{...opts,status:'shipping'},now);assert.equal(a.units,5);assert.equal(a.summary.matchingOrders,1);
a=aggregateAnalytics(rows,{...opts,status:'completed'},now);assert.equal(a.units,5);
a=aggregateAnalytics(rows,{...opts,period:'range',from:'2026-10-04',to:'2026-10-04',barPeriod:'yearly'},now);assert.equal(a.days.length,1);assert.equal(a.statusBars.length,12);assert.equal(a.statusBars[9].success,3);
a=aggregateAnalytics(rows,{...opts,period:'all'},now);assert.equal(a.granularity,'monthly');assert.equal(a.days[0].day,'2025-01');assert.equal(a.units,15);
assert.equal(aggregateAnalytics([],{...opts,period:'all'},now).days.length,1);
console.log('PASS: WIB calendar boundaries, inclusive date range, category amounts, status separation, expired payments, side-by-side counts and all-time buckets.');
