import assert from 'node:assert/strict';
import fs from 'node:fs';
const base='http://localhost:5173';
const login=await fetch(base+'/api/admin/login',{method:'POST',headers:{origin:base,'content-type':'application/json'},body:JSON.stringify({email:'qa-1790561889989@example.test',password:'local-test-password-2026'})});
assert.equal(login.status,200,'Local QA account from admin-api fixture required');
const cookie=login.headers.get('set-cookie').split(';')[0];
const bytes=fs.readFileSync('public/kopdes-logo.png');
async function upload(body,type='image/png',auth=true,origin=base){return fetch(base+'/api/admin/images',{method:'POST',headers:{origin,'content-type':type,...(auth?{cookie}:{})},body});}
assert.equal((await upload(bytes,'image/png',false)).status,401);
assert.equal((await upload(bytes,'image/png',true,'https://other.example')).status,403);
assert.equal((await upload('not an image')).status,400);
assert.equal((await upload('<svg/>','image/svg+xml')).status,400);
assert.equal((await upload(Buffer.alloc(12*1024*1024+1))).status,400);
for(const url of ['http://example.com/image.png','https://127.0.0.1/x.png','https://localhost/image.png','https://user:pass@example.com/x.png']) assert.equal((await upload(JSON.stringify({url}),'application/json')).status,400);
const jpeg=fs.readFileSync('public/catalog/anggur.jpg');
const jpegSaved=await upload(jpeg,'image/jpeg');assert.equal(jpegSaved.status,201);const jpegResult=await jpegSaved.json();assert.equal((await fetch(base+jpegResult.url)).headers.get('content-type'),'image/jpeg');
const saved=await upload(bytes);const result=await saved.json();assert.equal(saved.status,201,JSON.stringify(result));
const image=await fetch(base+result.url);assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/png');assert.deepEqual(Buffer.from(await image.arrayBuffer()),bytes);
const h={origin:base,'content-type':'application/json',cookie};
const products=(await (await fetch(base+'/api/admin/products',{headers:h})).json()).products;
const p=products.find(p=>p.id.startsWith('qa-'));assert.ok(p);
const {version,...product}=p;
assert.equal((await fetch(base+'/api/admin/products',{method:'PUT',headers:h,body:JSON.stringify({product:{...product,image:result.url},version})})).status,200);
const catalog=await (await fetch(base+'/api/catalog')).json();assert.equal(catalog.products.find(x=>x.id===p.id).image,result.url);
const staffData=await (await fetch(base+'/api/admin/staff',{headers:h})).json();
const staff=staffData.staff.map((s,i)=>i===0?{...s,image:result.url}:s);
assert.equal((await fetch(base+'/api/admin/staff',{method:'PUT',headers:h,body:JSON.stringify({staff,version:staffData.version})})).status,200);
assert.equal((await (await fetch(base+'/api/staff')).json()).staff[0].image,result.url);
assert.equal((await fetch(base+'/api/admin/staff',{method:'PUT',headers:h,body:JSON.stringify({staff:staffData.staff,version:staffData.version+1})})).status,200);
console.log('PASS: admin/CSRF boundaries, PNG byte roundtrip in R2, invalid format, 12 MB limit, unsafe URL rejection, product and staff persistence.');
