'use client';
import {useLanguage} from './language-context';
import {useEffect,useRef,useState} from 'react';
import {UserRound,LogOut,ShieldCheck,Heart,MapPin,ArrowRight,RefreshCw} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {useAccount} from './account-context';
import UserAvatar from './user-avatar';
import {toast} from 'sonner';
function GoogleSignIn(){
 const {t,language,setLanguage}=useLanguage();
 const host=useRef<HTMLDivElement>(null);const {refresh}=useAccount();const [state,setState]=useState<'loading'|'unconfigured'|'ready'|'error'|'signing'>('loading'),[message,setMessage]=useState('');
 useEffect(()=>{let cancelled=false;const abort=new AbortController();
 (async()=>{const r=await fetch('/api/auth/config',{signal:abort.signal});if(!r.ok)throw new Error(t("Login belum dapat dimuat."));const c:any=await r.json();if(cancelled)return;if(!c.ready){setState('unconfigured');return;}
 if(!(window as any).google?.accounts?.id){await new Promise<void>((resolve,reject)=>{const existing=document.querySelector<HTMLScriptElement>('script[data-google-identity]');const script=existing||document.createElement('script');const timeout=setTimeout(()=>reject(new Error(t("Google tidak dapat dimuat. Periksa koneksi atau pemblokir konten."))),12000);script.addEventListener('load',()=>{clearTimeout(timeout);resolve();},{once:true});script.addEventListener('error',()=>{clearTimeout(timeout);reject(new Error(t("Google tidak dapat dimuat.")));},{once:true});if(!existing){script.src='https://accounts.google.com/gsi/client';script.async=true;script.dataset.googleIdentity='true';document.head.appendChild(script);}});}
 if(cancelled||!host.current)return;const identity=(window as any).google.accounts.id;
 identity.initialize({client_id:c.clientId,nonce:c.nonce,auto_select:false,callback:async(response:{credential:string})=>{if(cancelled)return;setState('signing');try{const login=await fetch('/api/auth/google',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({credential:response.credential})});const data:any=await login.json();if(!login.ok)throw new Error(data.error);await refresh();toast.success(t("Berhasil masuk dengan Google."));}catch(e){setState('error');setMessage((e as Error).message);}}});identity.renderButton(host.current,{theme:'outline',size:'large',shape:'pill',text:'signin_with',locale:language,width:280});setState('ready');
 })().catch(e=>{if(!cancelled){setState('error');setMessage(e.message);}});return()=>{cancelled=true;abort.abort();};},[language]);
 return <><div ref={host} className="google-signin"/>{state==='loading'&&<p className="account-status" role="status">{t("Menyiapkan login Google…")}</p>}{state==='signing'&&<p className="account-status" role="status">{t("Memverifikasi akun Anda…")}</p>}{state==='unconfigured'&&<><button className="google-disabled" disabled><span>G</span> {t("Masuk dengan Google")}</button><p className="account-status">{t("Login Google belum diaktifkan. Untuk sementara, favorit dan alamat dapat disimpan di browser ini.")}</p></>}{state==='error'&&<p className="field-error" role="alert">{message} {t("Tutup lalu buka kembali panel ini untuk mencoba lagi.")}</p>}</>
}
export default function AccountPanel({open,onOpenChange,onAddress,onFavorites}:{open:boolean;onOpenChange:(v:boolean)=>void;onAddress:()=>void;onFavorites:()=>void}){
 const {t,language,setLanguage}=useLanguage();
 const {user,loading,saving,loadError,refresh,logout,profile}=useAccount();
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="account-dialog"><DialogHeader><div className="account-avatar"><UserAvatar user={user} size={48}/></div><DialogTitle>{user?t("Halo, ")+user.name.split(' ')[0]:t("Selamat datang di Kopdes")}</DialogTitle><DialogDescription>{user?user.email:t("Simpan yang kamu suka. Belanja dari desa jadi lebih mudah.")}</DialogDescription></DialogHeader>{loading?<p role="status">{t("Memuat akun…")}</p>:<>{loadError&&<div className="account-error"><p role="alert">{loadError}</p><button className="outline" onClick={refresh}><RefreshCw size={15}/> {t("Coba lagi")}</button></div>}{!user?<GoogleSignIn/>:<div className="account-connected"><ShieldCheck size={17}/> {t("Terhubung dengan akun Google")}</div>}<div className="account-shortcuts"><button onClick={()=>{onOpenChange(false);onFavorites();}}><Heart size={20}/><span>{t("Produk favorit")}<small>{profile.favorites.length} {t("produk tersimpan")}</small></span><ArrowRight size={17}/></button><button onClick={()=>{onOpenChange(false);onAddress();}}><MapPin size={20}/><span>{t("Alamat saya")}<small>{profile.address?profile.address.label+' · '+profile.address.city:t("Tambahkan alamat dan titik peta")}</small></span><ArrowRight size={17}/></button></div>{user?<button className="logout-button" disabled={saving} onClick={logout}><LogOut size={16}/> {t("Keluar dari akun")}</button>:<p className="storage-note">{t("Mode tamu · Data tersimpan hanya di browser ini, tidak otomatis dipindahkan ke akun Google.")}</p>}</>}</DialogContent></Dialog>
}
