'use client';
import {useEffect,useState,useRef} from 'react';
import {useRouter} from 'next/navigation';
import {Bell,Package,ShoppingBag} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {useAccount} from './account-context';
import {useLanguage} from './language-context';
import type {Notice} from '@/lib/notifications';
import {rupiah} from '@/lib/catalog';
export default function NotificationButton({onLogin}:{onLogin:()=>void}){const {user}=useAccount(),{t,language}=useLanguage(),router=useRouter();const [open,setOpen]=useState(false),[data,setData]=useState<{notices:Notice[];readAt:number;asOf:number}>({notices:[],readAt:0,asOf:0}),[error,setError]=useState(''),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[filter,setFilter]=useState('all'),[revision,setRevision]=useState(0);
useEffect(()=>{let active=true;let sequence=0;const controller=new AbortController();setData({notices:[],readAt:0,asOf:0});setError('');if(!user)return;async function refresh(){const current=++sequence;try{const r=await fetch('/api/notifications',{signal:controller.signal});const d:any=await r.json();if(!r.ok)throw Error(d.error);if(active&&current===sequence){setData(d);setError('');}}catch(e){if(active&&current===sequence)setError((e as Error).message);}finally{if(active&&current===sequence)setLoading(false);}}setLoading(true);void refresh();const timer=setInterval(refresh,30000);window.addEventListener('focus',refresh);window.addEventListener('kopdes-orders-changed',refresh);return()=>{active=false;controller.abort();clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('kopdes-orders-changed',refresh);};},[user?.id,revision]);
const scope=useRef(user?.id);scope.current=user?.id;const unread=data.notices.filter(n=>n.at>data.readAt).length;async function markRead(){const owner=user?.id;setSaving(true);try{const r=await fetch('/api/notifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({readAt:data.asOf})});if(!r.ok)throw Error('Notifikasi belum dapat disimpan.');if(scope.current===owner)setData(d=>({...d,readAt:Math.max(d.readAt,data.asOf)}));}catch(e){if(scope.current===owner)setError((e as Error).message);}finally{setSaving(false);}}
return <><button className="header-icon" onClick={()=>setOpen(true)} title={t('Notifikasi')} aria-label={t('Notifikasi')+(unread?`, ${unread}`:'')}><Bell size={20}/>{unread>0&&<b>{unread>99?'99+':unread}</b>}</button><Sheet open={open} onOpenChange={setOpen}><SheetContent className="notification-panel"><SheetHeader><SheetTitle>{t('Notifikasi')}</SheetTitle><SheetDescription>{t('Notifikasi pesanan dan perubahan harga atau stok produk.')}</SheetDescription></SheetHeader>{!user?<div className="empty"><Bell size={36}/><p>{t('Masuk untuk melihat notifikasi.')}</p><button className="primary" onClick={()=>{setOpen(false);onLogin();}}>{t('Masuk dengan Google')}</button></div>:<><div className="notification-tools"><div role="group" aria-label={t('Notifikasi')}>{[['all','Semua'],['order','Pesanan'],['product','Produk']].map(([value,label])=><button key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{t(label)}</button>)}</div><button className="detail-link" disabled={!unread||saving} onClick={markRead}>{t('Tandai semua dibaca')}</button></div>{error&&<div role="alert"><p>{t(error)}</p><button className="outline" onClick={()=>setRevision(v=>v+1)}>{t('Coba lagi')}</button></div>}{loading?<p role="status">{t('Memuat history')}</p>:<div className="notification-list">{data.notices.filter(n=>filter==='all'||n.kind===filter).map(n=><button key={n.id} className={'notification-item '+(n.at>data.readAt?'unread':'')} onClick={()=>{setOpen(false);router.push(n.kind==='order'?'/history?order='+encodeURIComponent(n.orderId!):'/produk');}}>{n.kind==='order'?<Package size={20}/>:<ShoppingBag size={20}/>}<span><strong>{t(n.key)}</strong>{n.kind==='order'?<small>#{n.orderId?.slice(0,8).toUpperCase()} · {t('Simulasi')}</small>:<><p>{t(n.name||'')}</p>{n.price!==n.oldPrice&&<small>{t('Harga')}: {rupiah(n.oldPrice!)} → {rupiah(n.price!)}</small>}{n.stock!==n.oldStock&&<small>{t('Stok')}: {n.oldStock} → {n.stock}{n.stock===0?' · '+t('Stok kosong'):''}</small>}</>}<time>{new Date(n.at).toLocaleString(language==='id'?'id-ID':'en-GB',{timeZone:'Asia/Jakarta',dateStyle:'medium',timeStyle:'short'})} WIB</time></span>{n.at>data.readAt&&<i aria-label={language==='id'?'Belum dibaca':'Unread'}/>}</button>)}{!data.notices.some(n=>filter==='all'||n.kind===filter)&&<div className="empty"><Bell size={32}/><h3>{t('Belum ada notifikasi')}</h3>{filter==='product'&&<p>{t('Belum ada perubahan harga atau stok sejak katalog mulai dipantau.')}</p>}</div>}</div>}<p className="notification-note">{t('Pembaruan diperiksa setiap 30 detik saat halaman terbuka.')}</p></>}</SheetContent></Sheet></>;
}
